http:
  host: "localhost"
  port: "8081"
db:
  host: "database-1.ca5yzoeinwgo.us-east-2.rds.amazonaws.com"
  port: "3306"
  password: "rootadmin"
  username: "admin"
  database: "sample"
sfdc:
  username: "dheeraj.mishra@apisero.com"
  password: "Apisero@123"
  token: "kGgQ1ZhwfZ8Ai60qfu68T1oxT"